apiVersion: v2
name: codeveros-user-service
description: Codeveros User Service Helm chart
type: application
version: 1.0.0
appVersion: 1.0.0
home: https://coveros.com
maintainers:
  - name: justin-coveros
    email: justin.hollingsworth@coveros.com
dependencies:
  - name: mongodb
    version: 10.3.3
    repository: https://charts.bitnami.com/bitnami
